### ISSUE TITLE
NoProxy

### ISSUE THREAD

**Issue by SVGV** [powernsx/powernsx.github.io#17]
In attempt it will be connected Connect-NsxServer -vCenterServer $vc

`Connection to NSX server  failed : Invoke-NsxRestMethod : The NSX API response received indicates a failure. 504 : Proxy Timeout ( The connection timed out.  ) : Response Body: 
 `

Can you add `-Noproxy` parameter, which would be broadcast in the `Invoke-NsxRestMethod` function?

**Comment by alagoutte** [comment]
Hi,

I think, it will be better to open on https://github.com/vmware/powernsx/issues

**Comment by SVGV** [comment]
Ok.

**Comment by pandom** [comment]
Closed - powernsx documentation issues are filed here and powernsx issues are filed at GitHub.com/vmware/powernsx.
