### ISSUE TITLE
Clarify manual installation instructions for Windows

### ISSUE THREAD

**Issue by daleshaw** [powernsx/powernsx.github.io#18]
Minor doc-bug: The **Manual Install - Windows** section of the [Getting Started](https://powernsx.github.io/get-started#manualInstallwindows) guide needs an update to make it clear that the .psm1 and .psd1 files should be placed in a directory named **PowerNSX**. 

In my case, `%ProgramFiles%\Common Files\Modules\PowerNSX` was not already in `$env:PSModulePath`, so I favoured the `%UserProfile%\Documents\WindowsPowerShell\Modules` option. I placed the .psm1/.psd1 files in this directory but PowerNSX didn't auto-load.

After being put through to the Level 8 PowerNSX IT Service Desk, I was advised to create the directory `%UserProfile%\Documents\WindowsPowerShell\Modules\PowerNSX` and place the files within it.

Success!

The update could be as simple as updating the _Current User_ folder/destination to include \PowerNSX at the end of the path.

**Comment by nmbradford** [comment]
Yup thanks @daleshaw .  I had asked admin to fix this, but obviously he didnt get round to it ;).  Errm @pandom :D?

**Comment by pandom** [comment]
Thanks Dale for the update and contribution. 

Fixed by pull #19
